### ISSUE TITLE
Integration Fails To Load After Upgrading HA 2026.2.3

### ISSUE THREAD

**Issue by wormuths** [uvjim/linksys_velop#576]
After upgrading from 2026.1.3 to 2026.2.3, the Velop Integration Fails To Load.  

`Logger: homeassistant.config_entries
Source: config_entries.py:730
First occurred: 5:02:26 PM (2 occurrences)
Last logged: 5:02:26 PM

Error importing platform config_flow from integration linksys_velop to set up linksys_velop configuration entry: cannot import name 'SsdpServiceInfo' from 'homeassistant.components.ssdp' (/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py)`

Another relevant error...

`Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 5:02:26 PM (1 occurrence)
Last logged: 5:02:26 PM

Detected blocking call to import_module with args ('custom_components.linksys_velop.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 928, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 672, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 728, in __async_setup_with_context await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")`

**Comment by uvjim** [comment]
Not am issue im seeing here and im running Home Assistant `2026.2.3`. Please make sure that you're running the latest version of the integration. The last time anything was touched around that import was a year ago to address a depreciation warning.

**Comment by wormuths** [comment]
Unreal...

For some reason, this integration wasn't even showing in HACS, so it never detected or updated in over a year.  I've had that with other HACS components as well.  I updated, and all is well.

Sorry to waste your time.  Thanks for keeping up with this integration, it's very helpful.
